---
title: 'Markov Chain '
author: "Rasul Ibragimov"
date: "Due March 16, 2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r libraries and data, message = FALSE, warning = FALSE}
library(ISLR2)
library(ggplot2)
library(dplyr)

```

```{r}
RA <- matrix(1:64, nrow = 8, ncol = 8)
RA <- rbind(c(1,2,2,2,3,3,3,4),c(0,1,1,1,2,2,2,3),c(0,1,1,1,2,2,2,3),c(0,1,1,1,2,2,2,3),c(0,0,0,0,1,1,1,2),c(0,0,0,0,1,1,1,2),c(0,0,0,0,1,1,1,2),c(0,0,0,0,0,0,0,1))
```


```{r}
RB <- matrix(1:64, nrow = 8, ncol = 8)
RB <- rbind(c(0,1,1,1,2,2,2,3),c(0,0,0,0,1,1,1,2),c(0,0,0,0,1,1,1,2),c(0,0,0,0,1,1,1,2),c(0,0,0,0,0,0,0,1),c(0,0,0,0,0,0,0,1),c(0,0,0,0,0,0,0,1),c(0,0,0,0,0,0,0,0))
```

```{r}
detach(t1)
```



```{r}

df <- data.frame(matrix(ncol = 25, nrow = 25))

tree <- function(X,Y){

  df <- data.frame(matrix(data = 0L, ncol = 25, nrow = 25))
  Y2 <- Y %>% filter(NO. == X)
  Y2 <-Y2[Y2 == "-"] <- "0"
  Y2$HR <- as.integer(Y2$HR)
  Y2$AB <- as.integer(Y2$AB)
  Y2$H <- as.integer(Y2$H)
  Y2$"2B" <- as.integer(Y2$"2B")
  Y2$"3B" <- as.integer(Y2$"3B")
  Y2$BB <- as.integer(Y2$BB)
  p_HR <- Y2$HR/Y2$AB
  p_SO <- ((Y2$H-(Y2$"2B"+Y2$"3B"+Y2$HR))/Y2$AB) + (Y2$BB/Y2$AB)
  p_1B <- ((Y2$H-(Y2$"2B"+Y2$"3B"+Y2$HR))/Y2$AB)
  p_2B <- Y2$"2B"/Y2$AB
  p_3B <- Y2$"3B"/Y2$AB
  p_BB <- Y2$BB/Y2$AB
  P_OUT <- 1 - ((Y2$HR/Y2$AB)+(((Y2$H-(Y2$"2B"+Y2$"3B"+Y2$HR))/Y2$AB) + (Y2$BB/Y2$AB))+((Y2$H-(Y2$"2B"+Y2$"3B"+Y2$HR))/Y2$AB)+(Y2$"2B"/Y2$AB)+(Y2$"3B"/Y2$AB)+(Y2$BB/Y2$AB))
    
    
  df[25,25] <- 1
  df[1:8,1] <- p_HR
  df[1,2] <- df[2,5] <- p_SO
  df[3,2] <- df[4,2] <- df[7,2] <- df[5,5] <- df[6,5] <- df[8,5] <- p_1B
  df[1,3] <- df[3,3] <- df[4,3] <- df[7,3] <- df[2,7] <- df[5,7] <- df[6,7] <- df[8,7] <- p_2B
  df[1:8,4] <- p_3B
  df[3,5] <- df[4,6] <- df[5:8,8] <- p_BB
  
  
  df[9:16,9] <- p_HR
  df[9,10] <- df[10,13] <- p_SO
  df[11,10] <- df[12,10] <- df[15,10] <- df[13,13] <- df[14,13] <- df[16,13] <- p_1B
  df[9,11] <- df[11,11] <- df[12,11] <- df[15,11] <- df[10,15] <- df[13,15] <- df[14,15] <- df[16,15] <- p_2B
  df[9:16,12] <- p_3B
  df[11,13] <- df[12,14] <- df[13:16,16] <- p_BB
  
  df[17:24,17] <- p_HR
  df[17,18] <- df[18,21] <- p_SO
  df[19,18] <- df[20,18] <- df[23,18] <- df[21,21] <- df[22,21] <- df[24,21] <- p_1B
  df[17,19] <- df[19,19] <- df[20,19] <- df[23,19] <- df[18,23] <- df[21,23] <- df[22,23] <- df[24,23] <- p_2B
  df[17:24,20] <- p_3B
  df[19,21] <- df[20,22] <- df[21:24,24] <- p_BB
  
  df[1,9] <- df[2,10] <- df[3,11] <- df[4,12] <- df[5,13] <- df[6,14] <- df[7,15] <- df[8,16] <- df[9,17] <- df[10,18] <- df[11,19] <- df[12,20] <- df[13,21] <- df[14,22] <- df[15,23] <- df[16,24] <- df[17:24,25] <- P_OUT
  

  
  df
  
}
df<-tree(2,t)

```


```{r}
Softball_data <- read_excel("~/Desktop/Softball_data.xlsx")
t <- Softball_data


```



```{r}
t2 <- t %>% filter(NO. == 12)
t2$HR <- as.integer(t2$HR)
t2$AB <- as.integer(t2$AB)

d <- t2$HR/t2$AB
d
```



```{r}
Un_plus_one <- function(Un, P, R){
  # Un: the 21 x 25 Un matrix from the previous iteration
  # The j^th row of Un indicates that (j-1) runs have scored this inning
  # P: the 25 x 25 transition matrix for the batter
  # R: the 25 x 25 "runs" matrix indicating how many runs scored on a transition
  
  # First we subset the P matrix into P0, P1, P2, P3, P4
  # where Pk is a matrix with the entry of P if the corresponding entry of R is k and 0 otherwise
  
  # These should get the correct entries but the resulting matrices might be shaped wrong
  P0 <- P * (R == 0)
  P1 <- P * (R == 1)
  P2 <- P * (R == 2)
  P3 <- P * (R == 3)
  P4 <- P * (R == 4)
  
  # Now we create the U_(n+1) matrix
  
  Unplus <- matrix(0, nrow = 21, ncol = 25)
  
  # The first 4 rows of the matrix have only partial sums
  
  # We do indeed right-multiply by the transition matrix so this is right
  # There's a chance that dimensions drop somewhere and this doesn't work
  Unplus[1,] <- Un[1,] %*% P0
  Unplus[2,] <- Un[2,] %*% P0 + Un[1,] %*% P1
  Unplus[3,] <- Un[3,] %*% P0 + Un[2,] %*% P1 + Un[1,] %*% P2
  Unplus[4,] <- Un[4,] %*% P0 + Un[3,] %*% P1 + Un[2,] %*% P2 + Un[1,] %*% P3
  
  # The last 17 rows of the matrix should have full sums
  
  # This part should work if the previous section of code works
  for (j in 5:21){
    Unplus[j,] <- Un[j,] %*% P0 + Un[j-1, ] %*% P1 + Un[j-2, ] %*% P2 + Un[j-3, ] %*% P3 + Un[j-4, ] %*% P4
  }
  
  return(Unplus)
  
}
```



